FROM centos:centos7

# https://webtatic.com/packages/php71/
#RUN rpm -Uvhi https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && yum update -y && yum install -y git mc vim httpd mod_php71w php71w-bcmath php71w-cli php71w-gd php71w-ldap php71w-mbstring php71w-mcrypt php71w-mssql php71w-odbc php71w-pear php71w-pecl-memcached php71w-pgsql php71w-soap php71w-xml php71w-devel gcc make uuid-devel libuuid-devel && pecl channel-update pecl.php.net && pecl install pthreads uuid
RUN rpm -Uvhi https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && yum update -y && yum install -y epel-release wget && cd /etc/yum.repos.d && wget https://repo.codeit.guru/codeit.el`rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release)`.repo --no-check-certificate && yum install -y git mc vim httpd mod_php71w php71w-bcmath php71w-cli php71w-gd php71w-ldap php71w-mbstring php71w-mcrypt php71w-mssql php71w-odbc php71w-pear php71w-pecl-memcached php71w-pgsql php71w-soap php71w-xml php71w-devel gcc make uuid-devel libuuid-devel && pecl channel-update pecl.php.net && pecl install uuid

#RUN echo -e "\nextension=pthreads.so" >> /etc/php.ini
RUN echo -e '\nextension=uuid.so' >> /etc/php.ini
RUN echo -e "\ndate.timezone=America/Denver" >> /etc/php.ini
RUN perl -pi -e 's#upload_max_filesize = 2M#upload_max_filesize = 20M#g' /etc/php.ini
RUN perl -pi -e 's#memory_limit = 128M#memory_limit = 1024M#g' /etc/php.ini
RUN perl -pi -e 's#max_execution_time = 30#max_execution_time = 240#g' /etc/php.ini
RUN echo -e '\nshort_open_tag=On' >> /etc/php.ini
