FROM centos:centos7

# https://webtatic.com/packages/php72/
# https://crosp.net/blog/administration/install-latest-apache-server-centos-7/
RUN rpm -Uvhi https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && yum update -y && yum install -y git mc vim httpd mod_php72w php72w-opcache php72w-bcmath php72w-cli php72w-common php72w-gd php72w-ldap php72w-mbstring php72w-mcrypt php72w-mssql php72w-odbc php72w-pear php72w-pecl-memcached php72w-pgsql php72w-soap php72w-xml php72w-devel gcc make uuid-devel libuuid-devel && pecl channel-update pecl.php.net && pecl install uuid
#RUN rpm -Uvhi https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm && yum update -y && yum install -y git mc vim httpd mod_php72w php72w-opcache php72w-bcmath php72w-cli php72w-common php72w-gd php72w-ldap php72w-mbstring php72w-mcrypt php72w-mssql php72w-odbc php72w-pear php72w-pecl-memcached php72w-pgsql php72w-soap php72w-xml php72w-devel gcc make uuid-devel libuuid-devel && pecl channel-update pecl.php.net && pecl install pthreads uuid

#RUN echo -e "\nextension=pthreads.so" >> /etc/php.ini
RUN echo -e '\nextension=uuid.so' >> /etc/php.ini
RUN echo -e "\ndate.timezone=America/Denver" >> /etc/php.ini
RUN perl -pi -e 's#upload_max_filesize = 2M#upload_max_filesize = 20M#g' /etc/php.ini
RUN perl -pi -e 's#memory_limit = 128M#memory_limit = 1024M#g' /etc/php.ini
RUN perl -pi -e 's#max_execution_time = 30#max_execution_time = 240#g' /etc/php.ini
RUN echo -e '\nshort_open_tag=On' >> /etc/php.ini
